name: Sync GitHub issues to Jira
on: [issues, issue_comment]

jobs:
  sync-issues:
    name: Sync issues to Jira
    runs-on: ubuntu-latest
    steps:
      - uses: canonical/sync-issues-github-jira@6e532ab8d30c561158f2ccbe702ef366dedcbb44 # v1
        with:
          webhook-url: ${{ secrets.JIRA_WEBHOOK_URL }}
